version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"

phases: 

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - target/mvn-hello.war
    - appspec.yml
  discard-paths: yes
